### ISSUE TITLE
warnings componentWillReceiveProps and useNativeDriver

### ISSUE THREAD

**Issue by daniimd** [alessiocancian/react-native-actionsheet#19]
I have these two alerts using the component, does anyone know if there is a way to remove them?

`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.`

`Animated: useNativeDriver was not specified. This is a required option and must be explicitly set to 'true' or 'false'`

Code: 

```
import { ActionSheetCustom as ActionSheet } from 'react-native-actionsheet'

  const refActionSheet = useRef(null);
  
  const showActionSheet = () => {
    if (refActionSheet.current) {
      refActionSheet.current.show();
    }
  }
  
  const options = [
    <Text>Deletar <Feather  name='trash-2' size={23} color={'#7c7c7c'} /></Text>,
    <Text>Editar <Feather  name='edit-2' size={23} color={'#7c7c7c'} /></Text>,
    <Text>Visualizar <Feather  name='eye' size={23} color={'#7c7c7c'} /></Text>,
    <Text>Cancelar</Text>
  ];

  <ActionSheet
      ref={refActionSheet}
      options={options}
      cancelButtonIndex={3}
      destructiveButtonIndex={0}
      onPress={(index) => {console.log(index) }}
    />
```

**Comment by alessiocancian** [comment]
This fork was initially created to fix those warnings, but you need to change your import from `react-native-actionsheet` to `@alessiocancian/react-native-actionsheet` because the maintainer of the old package doesn't uptade it since 2018.

Please note that since version 3.0.0 my package doesn't support expo, but if you are using expo you can still install `@alessiocancian/react-native-actionsheet@2.4.11` which is enough to fix the warnings.
