### ISSUE TITLE
problem with jest

### ISSUE THREAD

**Issue by misaku** [alessiocancian/react-native-actionsheet#2]
`Details:

    /media/michelkuguio/Novo volume/luizalabs/workspace/rodney/node_modules/@alessiocancian/react-native-actionsheet/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Platform } from 'react-native'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import IconBtn from 'react-native-vector-icons/FontAwesome';
      5 | import {Searchbar} from 'react-native-paper';
    > 6 | import ActionSheet from '@alessiocancian/react-native-actionsheet';
`

**Comment by alessiocancian** [comment]
I think the problem is not the library itself but `Platform` from `react-native`.
You should to mock it with jest and set `Platform.OS = "android"` (I don't think you can set iOS because this library uses native code for iOS), check [here (stackoverflow)](https://stackoverflow.com/questions/43161416/mocking-platform-detection-in-jest-and-react-native).
